// src/www/src/app/App.tsx
import styled from "styled-components";
import { FC } from "react";

import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

const Container = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
`;

const Title = styled.div`
  color: var(--primary);
  text-transform: uppercase;
  font-size: 4em;
  font-weight: 100;
`;

const Contents = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`;

const App: FC = () => {
  return (
    <Container>
      <Header />
      <Contents>
        <Title>Hello Sirocco!</Title>
        <p>Welcome to the next gen C++ servers.</p>
      </Contents>
      <Footer />
    </Container>
  );
};

export default App;

// src/www/src/App.svelte
<script lang="ts">
	export let name: string;
</script>

<main>
	<h1>Hello {name}!</h1>
	<p>Welcome to the new gen C++ servers.</p>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
